GET http://localhost:3000/todoList/todos HTTP/1.1

###
POST http://localhost:3000/todoList/todo HTTP/1.1
content-type: application/json

{
    "task": "Tidy your room please"
}

###
DELETE http://localhost:3000/todoList/todo/:todoId HTTP/1.1

###
PUT http://localhost:3000/auth/signup 

###
PUT http://localhost:3000/auth/login